version: "3"

services:

  backend:
    build: ./backend
    environment:
      - REQUEST_ORIGIN=http://frontend:5000
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    ports:
      - 5000:5000
